### ISSUE TITLE
🐛 visible door access policies in iOS app 

### ISSUE THREAD

**Issue by Whizma** [Dsek-LTH/member-page#1132]
## Short description of the bug
If I scroll to the bottom of the iOS app, I can see door access policies, even when not logged in. 

## To Reproduce
Go to the "iDét" tab, and scroll to the bottom.

## Expected behavior
I figure these policies should not be publicly visible? 

## Actual behavior
Policies are visible

## Environment (If applicable)
 App version 1.2.4
 iOS 16.5

**Comment by Macludde** [comment]
Hi! Thanks for bringing this up, but this is actually somewhat expected behavior. We changed access for doors so everyone can see who has access to what, in case they need to ask for someone to open it for them, or it they're just curios. But they can not modify anything.

However, users not logged in should not be able to see this. I went ahead and changed the access so only logged-in users see the screen.

Closing, go ahead an re-open if you do not agree with our access policy.
