### ISSUE TITLE
🐛 Private keys

### ISSUE THREAD

**Issue by pontussalenbo** [Dsek-LTH/member-page#908]
## Short description of the bug
A heads-up Private SSL key(s) are exposed [here](https://github.com/Dsek-LTH/member-page/blob/main/backend/services/core/src/ssl).

## Context
Private SSL keys are stored publicly, which could pose a potential security risk if not intended.

## Environment (If applicable)
 - Device(e.g. iPhone, desktop):
 - OS: (e.g. iOS):
 - Browser (e.g. chrome, safari):
 - Version (e.g. 22):

**Comment by 01ste02** [comment]
Thank you for the warning, it was brought to the attention of the right people. However, it turns out that they are just keys used for testing according to @oliverlevay and thus do not need to be kept hidden (since they have been published publicly elsewhere to be used for testing). For future reference, please submit potential security issues as security advisories using [this](https://github.com/Dsek-LTH/member-page/security/advisories) link. We appreciate your heads up though.
