### ISSUE TITLE
🐛 Time travel booking

### ISSUE THREAD

**Issue by julialovisakarlsson** [Dsek-LTH/member-page#966]
## Short description of the bug
You can book stuff in the past 🤨

## To Reproduce
Book stuff in the past 🤨

## Expected behavior
Error tbh

## Actual behavior
Not error tbh, it just works

## Context
<img width="1276" alt="Skärmavbild 2023-03-09 kl  16 13 00" src="https://user-images.githubusercontent.com/71255627/224068316-2e018123-2da5-424a-a577-06e73c4ae122.png">

**Comment by Macludde** [comment]
This is a feature, I like booking things in the past *closes issue*.

No but in all seriousness, I can actually see the benefit of doing this for logging purposes (for example: Someone forgets to book the guild car because they asked the KM in person and got an OK. Afterwards they can go in and add their booking to the page, so they are visible in the booking history). I'll close this for now, please re-open if you do not agree and this is a big issue.

**Comment by julialovisakarlsson** [comment]
Wellllll I think you should at least get a pop-up saying you actually have to get a booking in the past approved by the KM, it is not okay to borrow something without talking to the KM and just put it in the system afterwards. 

`"Det är inte tillåtet att boka något i efterhand utan att man kommit överens med Källarmästaren om detta först. Är du säker på att du vill göra denna bokningen?"`

`"You are not allowed to add a booking for a time that has already passed without a previous agreement with the Head of Facilities. Are you sure you want to make this booking?"`

This booking should be flagged somehow in the logs [senast ändrad senare än när bokningen började?], so that it's easy to find later, and perhaps have a special notification to the KM saying something like "... made a booking in the past" so that the KM would know to investigate the logs.
