### ISSUE TITLE
🐛 articleError when pressing links in news article

### ISSUE THREAD

**Issue by BardNilz** [Dsek-LTH/member-page#997]
## Short description of the bug
Whenever you press the link in a news article (i.e. the link posted at https://www.dsek.se/en/news/article/tandemstafetten-1 ), you get sent to a page stating "articleError". 

## To Reproduce
Press the link in a news article (i.e. the link posted at https://www.dsek.se/en/news/article/tandemstafetten-1 ).

## Expected behavior
Send the user to the expected link.

## Actual behavior
Gets sent to a page stating "articleError"

## Context
Screenshots or other data that is relevant to the bug.
![image](https://user-images.githubusercontent.com/80070896/228376264-36708670-9dd0-4dd4-a9ca-e1219fcb943e.png)

**Comment by Macludde** [comment]
This was an error on the person creating the article. The link in the post was correct, but they never changed the link in markdown so it linked to "url", which sent the user to `https://dsek.se/article/url`. I've fixed the article manually now.

Perhaps, however, there should be a more descriptive error message rather than just "articleError"? WDYT @danieladugyan?

**Comment by danieladugyan** [comment]
> This was an error on the person creating the article. The link in the post was correct, but they never changed the link in markdown so it linked to "url", which sent the user to `https://dsek.se/article/url`. I've fixed the article manually now.
> 
> Perhaps, however, there should be a more descriptive error message rather than just "articleError"? WDYT @danieladugyan?

Created a [draft issue](https://github.com/orgs/Dsek-LTH/projects/6/views/1?pane=issue&itemId=24741365) to address this.
